---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_GIRAFFE}
  labels:
    app: ${SERVICE_GIRAFFE}
spec:
  replicas: ${GIRAFFE_SCALE}
  selector:
    matchLabels:
      app: {{ project }}-{{ role }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ project }}-{{ role }}
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: NPM_CONFIG_LOGLEVEL
          value: info
        - name: GIRAFFE_HOST
          value: ${GIRAFFE_HOST}
        - name: GIRAFFE_SESSION_SECRET
          value: ${GIRAFFE_SESSION_SECRET}
        - name: GIRAFFE_SESSION_MAX_AGE
          value: '${GIRAFFE_SESSION_MAX_AGE}'
        - name: GIRAFFE_REDIS_SERVER
          value: ${GIRAFFE_REDIS_SERVER}
        - name: GIRAFFE_REDIS_PORT
          value: '${GIRAFFE_REDIS_PORT}'
        - name: GIRAFFE_REDIS_PWD
          value: ${GIRAFFE_REDIS_PWD}
        - name: GIRAFFE_RABBITMQ_URL
          value: ${GIRAFFE_RABBITMQ_URL}
        - name: WXAPP_ORYX_APP_ID
          value: ${WXAPP_ORYX_APP_ID}
        - name: WXAPP_ORYX_APP_SECRET
          value: ${WXAPP_ORYX_APP_SECRET}
        - name: SERVICE_CLASSIC_WEBHOST
          value: ${SERVICE_CLASSIC_WEBHOST}
        - name: SERVICE_POP_CORE_APPHOST
          value: ${SERVICE_POP_CORE_APPHOST}
        - name: SERVICE_SIMBA
          value: ${SERVICE_SIMBA}
        image: {{ image_name }}
        imagePullPolicy: IfNotPresent
        name: {{ project }}-{{ role }}
      imagePullSecrets:
      - name: default-secret
      nodeSelector:
        envnode: ${ENV_NODE_LABEL}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${SERVICE_GIRAFFE}
  name: ${SERVICE_GIRAFFE}
spec:
  selector:
    app: {{ project }}-{{ role }}
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8888
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-${SERVICE_GIRAFFE}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ${HOST_I_GIRAFFE}
      http:
        paths:
          - backend:
              serviceName: ${SERVICE_GIRAFFE}
              servicePort: 80
            path:
